SRCFILES := \
	src/a_actor.c \
	src/b_main.c \
	src/g_bob.c \
	src/g_font.c \
	src/g_menu.c \
	src/m_iter.c \
	src/m_load.c \
	src/m_map.c \
	src/r_actor.c \
	src/r_draw.c \
	src/r_fixed.c \
	src/r_flat.c \
	src/r_local.c \
	src/r_main.c \
	src/r_sector.c \
	src/r_wall.c \
	src/u_aabb.c \
	src/u_file.c \
	src/u_format.c \
	src/u_list.c \
	src/u_math.c \
	src/u_vec.c \
	src/w_pack.c \
	src/y_log.c \
	src/z_memory.c
